#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include "ch32_i2c_multi_gateway_final.h"
#include "ch32_vl53l4cd_gateway.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#define TAG "VL53L4CD_EXAMPLE"
#define MAX_NODES 6U
#define MAX_SENSORS 6U
#define DISCOVERY_START_MS 5000U
#define DISCOVERY_RETRY_MS 3000U
#define REDISCOVERY_MISSING_MS 10000U
#define REDISCOVERY_ONLINE_MS 30000U
#define SAMPLE_PERIOD_MS 200U
#define SAMPLE_COUNT 50U
typedef struct{ch32_i2c_multi_node_t*node;vl53l4cd_handle_t sensor;uint32_t samples;}sensor_slot_t;
static ch32_i2c_multi_node_t s_nodes[MAX_NODES];static size_t s_node_count;static sensor_slot_t s_slots[MAX_SENSORS];
static ch32_i2c_multi_node_t*find_node(uint8_t type,uint16_t token){for(size_t i=0;i<s_node_count;i++)if(s_nodes[i].device_type==type&&s_nodes[i].token==token)return&s_nodes[i];return NULL;}
static ch32_i2c_multi_node_t*merge_node(const ch32_i2c_multi_node_t*f){if(!f||!f->ready||!f->token)return NULL;ch32_i2c_multi_node_t*s=find_node(f->device_type,f->token);if(s){uint8_t old=s->node_id;*s=*f;if(old!=s->node_id)printf("[INF][CH32_I2C] node update token=0x%04X old=%u new=%u stable_ref_kept=1\n",s->token,old,s->node_id);return s;}if(s_node_count>=MAX_NODES)return NULL;s=&s_nodes[s_node_count++];*s=*f;printf("[INF][CH32_I2C] F2 confirmed node add token=0x%04X node=%u total=%u\n",s->token,s->node_id,(unsigned)s_node_count);return s;}
static sensor_slot_t*slot_for(ch32_i2c_multi_node_t*n){sensor_slot_t*free=NULL;for(size_t i=0;i<MAX_SENSORS;i++){if(s_slots[i].node==n)return&s_slots[i];if(!free&&!s_slots[i].node)free=&s_slots[i];}if(free)free->node=n;return free;}
static bool any_online(void){for(size_t i=0;i<MAX_SENSORS;i++)if(s_slots[i].sensor)return true;return false;}
static void start_sensor(ch32_i2c_multi_node_t*n){sensor_slot_t*s=slot_for(n);if(!s||s->sensor||s->samples>=SAMPLE_COUNT)return;vl53l4cd_cfg_t cfg={.i2c_addr=VL53L4CD_I2C_ADDR_DEFAULT,.ch32_node=n,.bridge_timeout_ms=VL53L4CD_BRIDGE_TIMEOUT_MS,.data_ready_timeout_ms=VL53L4CD_DATA_READY_TIMEOUT_MS};int r=vl53l4cd_init(&s->sensor,&cfg);if(r){printf("[ERR][" TAG "] module init FAIL token=0x%04X node=%u err=%d\n",n->token,n->node_id,r);s->node=NULL;}}
static void discover_merge(uint32_t timeout){ch32_i2c_multi_node_t fresh[MAX_NODES]={0};size_t count=0;ch32_i2c_multi_result_t r=ch32_i2c_multi_discover_incremental(fresh,MAX_NODES,&count,timeout);printf("[INF][CH32_I2C] discovery result=%s fresh=%u stable_before=%u\n",ch32_i2c_multi_result_text(r),(unsigned)count,(unsigned)s_node_count);if(r!=CH32_I2C_MULTI_RESULT_OK&&!count){printf("[WRN][CH32_I2C] discovery keep existing stable=%u reason=FAILED_OR_TIMEOUT\n",(unsigned)s_node_count);return;}for(size_t i=0;i<count;i++){ch32_i2c_multi_node_t*n=merge_node(&fresh[i]);if(!n)continue;r=ch32_i2c_multi_scan(n);if(r==CH32_I2C_MULTI_RESULT_OK){printf("[INF][CH32_I2C] full scan token=0x%04X node=%u count=%u addrs=",n->token,n->node_id,n->i2c_addr_count);if(n->i2c_addr_count==0U)printf("NONE");for(uint8_t a=0U;a<n->i2c_addr_count;a++)printf("%s0x%02X",a?",":"",n->i2c_addrs[a]);printf("\n");if(n->scan_bus_diag_valid)printf("[INF][CH32_I2C] bus lines token=0x%04X node=%u before_scl=%u before_sda=%u recovery=%u after_scl=%u after_sda=%u\n",n->token,n->node_id,n->scan_scl_before_high,n->scan_sda_before_high,n->scan_recovery_ok,n->scan_scl_after_high,n->scan_sda_after_high);}else{printf("[ERR][CH32_I2C] full scan FAIL token=0x%04X node=%u result=%s\n",n->token,n->node_id,ch32_i2c_multi_result_text(r));}bool found=false;r=ch32_i2c_multi_probe(n,VL53L4CD_I2C_ADDR_DEFAULT,&found);if(r!=CH32_I2C_MULTI_RESULT_OK){printf("[ERR][CH32_I2C] downstream probe FAIL token=0x%04X node=%u result=%s\n",n->token,n->node_id,ch32_i2c_multi_result_text(r));continue;}printf("[INF][CH32_I2C] downstream scan node=%u token=0x%04X result=OK addr_0x29=%s\n",n->node_id,n->token,found?"PRESENT":"ABSENT");if(found)start_sensor(n);}}
void app_main(void){ch32_i2c_multi_config_t cfg;ch32_i2c_multi_default_config(&cfg);cfg.discovery_timeout_ms=DISCOVERY_START_MS;cfg.command_timeout_ms=VL53L4CD_BRIDGE_TIMEOUT_MS;if(ch32_i2c_multi_init(&cfg)!=0){printf("[ERR][CH32_CAN_CORE] init FAIL\n");return;}printf("[INF][CH32_CAN_CORE] init OK\n");discover_merge(DISCOVERY_START_MS);TickType_t last=xTaskGetTickCount();while(true){for(size_t i=0;i<MAX_SENSORS;i++)if(s_slots[i].sensor&&s_slots[i].samples<SAMPLE_COUNT){vl53l4cd_result_t d;int r=vl53l4cd_read(s_slots[i].sensor,&d);if(!r)printf("[INF][VL53L4CD] data valid=1 mm=%u out_of_range=0 status=%u token=0x%04X node=%u\n",d.distance_mm,d.range_status,s_slots[i].node->token,s_slots[i].node->node_id);else if(r==ERR_VL53L4CD_OUT_OF_RANGE)printf("[WRN][VL53L4CD] OUT RANGE mm=%u status=%u token=0x%04X node=%u\n",d.distance_mm,d.range_status,s_slots[i].node->token,s_slots[i].node->node_id);else printf("[ERR][VL53L4CD] module runtime FAIL token=0x%04X node=%u err=%d\n",s_slots[i].node->token,s_slots[i].node->node_id,r);if(++s_slots[i].samples==SAMPLE_COUNT){(void)vl53l4cd_deinit(s_slots[i].sensor);s_slots[i].sensor=NULL;}}uint32_t period=any_online()?REDISCOVERY_ONLINE_MS:REDISCOVERY_MISSING_MS;if(xTaskGetTickCount()-last>=pdMS_TO_TICKS(period)){printf("[INF][" TAG "] rediscovery begin keep_existing_i2c=1\n");discover_merge(DISCOVERY_RETRY_MS);last=xTaskGetTickCount();}vTaskDelay(pdMS_TO_TICKS(SAMPLE_PERIOD_MS));}}
